service: aws-python-sqs-worker-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer

functions:
  consumer:
    handler: handler.consumer
    destinations:
      onSuccess:
        arn:
          Fn::GetAtt: [TransferProcessedTopic, Arn]

resources:
  Resources:
    TransferProcessedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: succeded-transfer-orders

plugins:
  - serverless-lift
  - serverless-python-requirements

package:
  patterns:
    - "!node_modules/**"
